version: '3'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pss
      MYSQL_DATABASE: pss
      MYSQL_USER: pss
      MYSQL_PASSWORD: pss
  backend:
    build: .
    restart: unless-stopped
    environment:
      - PSS_DATABASE_URL=jdbc:mysql://db:3306/pss
      - PSS_ADMIN_USER
      - PSS_ADMIN_PASSWORD
    ports:
      - 8080:8080
    depends_on:
      - db
